//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarasov_olimp
{
    using System;
    using System.Collections.Generic;
    
    public partial class dop_chast
    {
        public int id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public System.DateTime date_input { get; set; }
        public Nullable<int> id_into_repair { get; set; }
    
        public virtual into_repair into_repair { get; set; }
    }
}
