//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarasov_olimp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Histori_remove
    {
        public int id { get; set; }
        public int From { get; set; }
        public int To { get; set; }
        public System.DateTime Time_Date { get; set; }
        public Nullable<int> id_machine { get; set; }
    
        public virtual Fillial Fillial { get; set; }
        public virtual Fillial Fillial1 { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
