//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarasov_olimp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepairDBEntities : DbContext
    {
        public RepairDBEntities()
            : base("name=RepairDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dop_chast> dop_chast { get; set; }
        public virtual DbSet<Fillial> Fillial { get; set; }
        public virtual DbSet<Histori_remove> Histori_remove { get; set; }
        public virtual DbSet<into_repair> into_repair { get; set; }
        public virtual DbSet<kind_repair> kind_repair { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
