//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarasov_olimp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.into_repair = new HashSet<into_repair>();
            this.into_repair1 = new HashSet<into_repair>();
        }
    
        public int id { get; set; }
        public string Fname { get; set; }
        public string Sname { get; set; }
        public string Lname { get; set; }
        public string Dolgnost { get; set; }
        public System.DateTime Date_begin { get; set; }
        public System.DateTime Date_end { get; set; }
        public Nullable<int> id_fillial { get; set; }
    
        public virtual Fillial Fillial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<into_repair> into_repair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<into_repair> into_repair1 { get; set; }
    }
}
